_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.17
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
